name: warung_ajib
description: Aplikasi UMKM Warung Ajib
publish_to: 'none' # Remove this line if you intend to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.20
  path_provider: ^2.0.11

flutter:
  uses-material-design: true
  assets:
    - assets/products/
    - assets/products/
    - assets/products/
    - assets/